apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-spring
  namespace: spring
spec:
  selector:
    matchLabels:
      app: test-spring
  replicas: 1
  template:
    metadata:
      labels:
        app: test-spring
    spec:
      containers:
      - name: test-spring
        image: aimhigh/test-spring:latest
      serviceAccount: spring-sa
