apiVersion: v1
kind: Service
metadata:
  name: test-spring
  namespace: spring
spec:
  selector:
    app: test-spring
  ports:
    - name: test-spring
      port: 8080
      nodePort: 30080
  type: NodePort
